name: flutter_list_ui
description: A Flutter package that provides a collection of list-related widgets with consistent styling and behavior.
version: 1.3.9
homepage: https://github.com/tokkaiiii/flutter_list_ui
repository: https://github.com/tokkaiiii/flutter_list_ui

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Windows 호환성 설정
publish_to: 'none'
publish_config:
  windows:
    file_locks: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 